name: Not-Yet-Implemented Protocol Report
description: If you are sure that the ip/host information you have provided is correct but the integration can not establish a connection to your Tibber pulse
labels: enhancement
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go though this short checklist - TIA
      options:
        - label: I have installed the **latest** release (or BETA) version of the integration and home assistant.
          required: true
        - label: I have checked that the issue still exist with a none default __Node number__ (not equals 1) - check 2,3 or 4
          required: true
        - label: I have prepared DEBUG log output (for technical issues) |
            In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
          required: true
  - type: dropdown
    id: system
    attributes:
      label: Meter type? |
        check your http://[YOUR-PULSE-IP]/nodes/1/config
      multiple: false
      options:
        - Auto scan mode
        - IEC-62056-21 (IR)
        - Logarex
        - SML 1.04
        - Impressions (Blinks / kwh) using ambient sensor
        - Impressions (Blinks / kwh) using ir sensor
    validations:
      required: true
  - type: textarea
    id: data
    attributes:
      label: Output of the Tibber webfrontent data.json |
        check http://[YOUR-PULSE-IP]/nodes/1/data or http://[YOUR-PULSE-IP]/data.json?node_id=1
      placeholder: "Please copy and paste the output of your http://[YOUR-PULSE-IP]/data.json?node_id=1 - you might like to create/check the possible DEBUG log output of the home assistant integration"
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Integration DEBUG log
      placeholder: "Please copy and paste of the DEBUG log output of the integration"
      render: shell
  - type: textarea
    id: content
    attributes:
      label: Any additional description
      placeholder: "Can you provide any additional information?"